version: '3.8'

services:
  nginx:
    build:
      context: .
      dockerfile: ./docker/nginx/Dockerfile
    ports:
      - '80:80'
    volumes:
      - ./app/api/static:/code/static/
    depends_on:
      - app
  app:
    build:
      context: .
      dockerfile: ./docker/app/Dockerfile
    command: gunicorn app.wsgi:application --bind 0.0.0.0:8000
    ports:
      - '8000:8000'
    expose:
      - 8000
    volumes:
      - ./app:/code/app